//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMCSQL03Entities2 : DbContext
    {
        public CMCSQL03Entities2()
            : base("name=CMCSQL03Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblDivision> tblDivisions { get; set; }
        public virtual DbSet<tblCarrier> tblCarriers { get; set; }
        public virtual DbSet<tblClient> tblClients { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblEndUse> tblEndUses { get; set; }
        public virtual DbSet<tblOrderSource> tblOrderSources { get; set; }
        public virtual DbSet<tblOrderType> tblOrderTypes { get; set; }
        public virtual DbSet<tblBOLComment> tblBOLComments { get; set; }
        public virtual DbSet<tblClientContact> tblClientContacts { get; set; }
        public virtual DbSet<tblPreferredCarrierList> tblPreferredCarrierLists { get; set; }
        public virtual DbSet<tblOrderItem> tblOrderItems { get; set; }
        public virtual DbSet<tblOrderMaster> tblOrderMasters { get; set; }
    }
}
