//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int ClientID { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public Nullable<int> GlobalClientID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string CMCLocation { get; set; }
        public string CustomerReference { get; set; }
        public string CMCLongCustomer { get; set; }
        public Nullable<bool> MSDS { get; set; }
        public Nullable<bool> TDS { get; set; }
        public Nullable<bool> COA { get; set; }
        public string DocumentDirectory { get; set; }
        public string MSDS_Folder { get; set; }
        public string TDS_Folder { get; set; }
        public string COA_Folder { get; set; }
        public string SP_ServiceSummary { get; set; }
        public string SP_Detail1 { get; set; }
        public string SP_Detail2 { get; set; }
        public string SP_Detail3 { get; set; }
        public string SP_Detail4 { get; set; }
        public string SP_Detail5 { get; set; }
        public Nullable<System.DateTime> SP_RevDate { get; set; }
        public string SP_CommValue { get; set; }
        public string SP_COARequired { get; set; }
        public string SP_TDSRequired { get; set; }
        public string SP_MSDSLanguage { get; set; }
        public string SP_Freezable { get; set; }
        public string SP_LabelLanguage { get; set; }
        public string SP_Expedite { get; set; }
        public string BOLComment { get; set; }
    }
}
