//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientContact
    {
        public int ClientContactID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ContactType { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Account { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Territory { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public string Company_MDB { get; set; }
        public string Location_MDB { get; set; }
    }
}
