//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderType
    {
        public int OrderTypeID { get; set; }
        public string OrderType { get; set; }
        public string Description { get; set; }
        public Nullable<int> LegacyID { get; set; }
    }
}
