//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderMaster
    {
        public int ORDERID { get; set; }
        public Nullable<int> CMCORDER { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string CUSTORDNUM { get; set; }
        public Nullable<int> WebOrderID { get; set; }
        public string REFNUM { get; set; }
        public string DIVISION { get; set; }
        public string ORDERTYPE { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string COMPANY { get; set; }
        public string STREET { get; set; }
        public string STREET2 { get; set; }
        public string STREET3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string country { get; set; }
        public string ATTENTION { get; set; }
        public string EMAIL { get; set; }
        public string SALESREP { get; set; }
        public string SALES_Email { get; set; }
        public string SALES_Dept { get; set; }
        public string SALES_Terr { get; set; }
        public string Sales_Phone { get; set; }
        public string Sales_Fax { get; set; }
        public string CSR { get; set; }
        public string CSR_Email { get; set; }
        public string MKTG { get; set; }
        public string Distributor { get; set; }
        public string REQ { get; set; }
        public string REQ_PHONE { get; set; }
        public string REQ_fax { get; set; }
        public string REQ_email { get; set; }
        public string EndUse { get; set; }
        public string Ship_Via { get; set; }
        public string Ship_Acct { get; set; }
        public string Phone { get; set; }
        public string Source { get; set; }
        public string Fax { get; set; }
        public string Tracking { get; set; }
        public string Special { get; set; }
        public string SpecialInternal { get; set; }
        public Nullable<bool> Lit { get; set; }
        public string Region { get; set; }
        public Nullable<bool> COA { get; set; }
        public string CID { get; set; }
        public string CustACCT { get; set; }
        public string ACode { get; set; }
        public string ImportFile { get; set; }
        public Nullable<System.DateTime> Import_dateline { get; set; }
        public string Timing { get; set; }
        public string Volume { get; set; }
        public string PONumber { get; set; }
        public string FollowUp { get; set; }
        public string CustOrderType { get; set; }
        public Nullable<System.DateTime> EMNRequestDate { get; set; }
        public Nullable<int> EMNTotalItems { get; set; }
        public string EMNReqName { get; set; }
        public string PickZone { get; set; }
        public string BillTo_COMPANY { get; set; }
        public string BillTo_STREET { get; set; }
        public string BillTo_STREET2 { get; set; }
        public string BillTo_STREET3 { get; set; }
        public string BillTo_CITY { get; set; }
        public string BillTo_STATE { get; set; }
        public string BillTo_ZIP { get; set; }
        public string BillTo_Country { get; set; }
        public string BillTo_Attention { get; set; }
        public string Misc1 { get; set; }
        public string Misc2 { get; set; }
        public string SAPNUM { get; set; }
        public string CMCLEGACYNUM { get; set; }
        public Nullable<int> CMCLEGACYNUM_INTEGER { get; set; }
        public Nullable<bool> ApprovalNeeded { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedByDate { get; set; }
        public string Misc1_bak { get; set; }
        public string Misc2_bak { get; set; }
        public Nullable<System.DateTime> ImportTimestamp { get; set; }
        public string CMCLocation { get; set; }
        public string CUSTOMERold { get; set; }
        public string LotusNotesRef { get; set; }
        public Nullable<bool> Restricted { get; set; }
        public string Approver { get; set; }
        public Nullable<int> ExternalID { get; set; }
        public Nullable<bool> BlackList { get; set; }
        public Nullable<System.DateTime> ISPOrderDate { get; set; }
        public string ISPBU { get; set; }
        public string MarketingManager { get; set; }
        public string Salesman { get; set; }
        public string Department { get; set; }
        public string ExportFileName { get; set; }
        public Nullable<System.DateTime> ExportFileDate { get; set; }
        public string Div { get; set; }
        public Nullable<bool> TechData { get; set; }
        public string SPSTaxID { get; set; }
        public string SPSCurrency { get; set; }
        public string SPSShippedWt { get; set; }
        public string SPSFreightCost { get; set; }
        public string InvoiceCompany { get; set; }
        public string InvoiceTitle { get; set; }
        public string InvoiceFirstName { get; set; }
        public string InvoiceLastName { get; set; }
        public string InvoiceAddress1 { get; set; }
        public string InvoiceAddress2 { get; set; }
        public string InvoiceAddress3 { get; set; }
        public string InvoiceCity { get; set; }
        public string InvoiceStateProv { get; set; }
        public string InvoicePostalCode { get; set; }
        public string InvoicePhone { get; set; }
        public string ISPVCPRating { get; set; }
        public Nullable<bool> Rush { get; set; }
        public Nullable<bool> Return { get; set; }
        public string Location { get; set; }
        public string BillingGroup { get; set; }
        public string Test { get; set; }
        public string Application { get; set; }
        public Nullable<bool> Kits { get; set; }
        public Nullable<bool> RegulatoryHold { get; set; }
        public string ShipFromLocation { get; set; }
        public string ShipFromLocationContact { get; set; }
        public string EMNOrderType { get; set; }
        public Nullable<System.DateTime> EMNApprovedDate { get; set; }
        public Nullable<System.DateTime> EMNDeliveryDate { get; set; }
        public string EMNBO { get; set; }
        public string EMNChargeCode { get; set; }
        public string EMNShipFromPlant { get; set; }
        public string EMNCustRep1 { get; set; }
        public string EMNCustRep2 { get; set; }
        public string EMNCustRep3 { get; set; }
        public string EMNReqRegion { get; set; }
        public string EMNReqCarrier { get; set; }
        public string CustDelivNum { get; set; }
        public string CustSAPNum { get; set; }
        public Nullable<bool> CSRFee { get; set; }
        public string BOLNote { get; set; }
        public string BillingCode { get; set; }
        public string SalesCode { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ShipRef { get; set; }
        public string CMCUser { get; set; }
        public string BusARea { get; set; }
        public Nullable<int> TotalOrderWeight { get; set; }
        public Nullable<System.DateTime> CustRequestDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> RequestedDeliveryDate { get; set; }
        public Nullable<int> CustTotalItems { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public string Location_MDB { get; set; }
        public string Company_MDB { get; set; }
    }
}
