//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreferredCarrierList
    {
        public int PreferredCarrierListID { get; set; }
        public string CountryCode { get; set; }
        public string Country { get; set; }
        public Nullable<bool> CommercialInvoice { get; set; }
        public string NonHaz_Sm { get; set; }
        public string NonHaz_Lg { get; set; }
        public string NonHazIncoTerms { get; set; }
        public string HazIATA_Sm { get; set; }
        public string HazIATA_Lg { get; set; }
        public string HazCarrierADR_LQ { get; set; }
        public string HazCarrierADR { get; set; }
        public string HazIncoTerms { get; set; }
        public string IncoTermsDSM { get; set; }
        public string NotesAlgemeen { get; set; }
        public string NotesIATA_ADR { get; set; }
        public string NonHazIncoTermsAshLand_Importer { get; set; }
        public string HazIncoTermsAshLand_Importer { get; set; }
        public string xxNonHazCarrier2ndChoice { get; set; }
        public Nullable<int> LegacyID { get; set; }
    }
}
